#!/bin/bash
#
#   /etc/rc.d/init.d/hangwatch
#
# hangwatch
# chkconfig: 2345 91 61
# description: Capture sysrq data

RETVAL=0
prog="hangwatch"
HANGWATCH=/usr/sbin/hangwatch
LOCK_FILE=/var/lock/subsys/hangwatch
config=/etc/sysconfig/hangwatch

# Source function library.
. /etc/init.d/functions

# sysconfig
[ -r $config ] && . $config || {
  echo "Error: unable to read $config"
  exit 6
  } >&2

start() {
    echo -n "Starting $prog: "
    daemon $HANGWATCH $OPTIONS && success || failure
    RETVAL=$?
    echo
    [ "$RETVAL" = 0 ] && touch $LOCK_FILE
}   

stop() {
    echo -n "Shutting down $prog: "
    killproc $HANGWATCH -HUP
    RETVAL=$?
    echo
    [ "$RETVAL" = 0 ] && rm -f $LOCK_FILE
}

restart() {
    stop
    start
}

case "$1" in
    start)
     start
    ;;
    stop)
     stop
    ;;
    status)
     status $HANGWATCH
    ;;
    restart)
     restart
    ;;
    reload)
    	echo -n $"Reloading $prog: "
    	killproc $HANGWATCH -HUP
    	RETVAL=$?
    	echo
    ;;
    condrestart)
      [ -f $LOCK_FILE ] && restart || :
    ;;
    *)
    echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
    RETVAL=3
esac
exit $RETVAL
